syntax on

set showcmd
set showmode
set number
set hlsearch

filetype off
" install: git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle 
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()
Bundle 'gmarik/vundle'
filetype plugin indent on
